# Lambda function

In [ ]:
x = lambda a : a + 10

print(x(5))

In [ ]:
x = lambda a, b : a * b
print(x(6, 7))

In [ ]:
def myfunc(n):
    return lambda a : a * n

mydoubler = myfunc(2)

mydoubler(13)

## Numpy code along


In [ ]:
# 'np' is the conventional alias for numpy
import numpy as np

#### Numpy arrays

In [ ]:
## one dimensional array is a vector
a = np.array([5,3,2])

In [ ]:
a.shape

#### Generate an array with random numbers

In [ ]:
np.random.seed(1002)
a = np.random.random((6,2))
a

### Other ways to create arrays

#### List to array

This works the same way whether you have a list of lists, a list of tuples, a tuple of lists, or a tuple of tuples.

In [13]:
lst_lst_lst = [[[1,2,3],[4,5,6],[7,8,9]]]
d = np.array(lst_lst_lst)
print(d.shape)

(1, 3, 3)


#### Constant arrays

In [14]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a, "\n")

b = np.ones((3,2))   # Create an array of all ones
print(b, "\n")

c = np.full((2,2), 7) # Create a constant array
print(c)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[7 7]
 [7 7]]


#### Sequential arrays

In [15]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.85402874,  0.49396181, -0.13071143],
       [-0.40312075, -0.97366226, -0.46746678],
       [-0.71792147,  1.22139331, -0.77720001]])

In [18]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 1, 3],
       [5, 9, 9],
       [2, 7, 5]])

#### Array Attributes

In [19]:
np.random.seed(123)
a = np.random.random((6,3))
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [20]:
a.shape

(6, 3)

In [21]:
a.size

18

In [22]:
a.ndim

2

In [23]:
a.dtype

dtype('float64')

In [30]:
b = np.array([1,3,8])

In [31]:
b.dtype

dtype('int32')

In [37]:
b.astype(np.int8)

array([1, 3, 8], dtype=int8)

In [38]:
b.itemsize

4

In [39]:
c = np.array([1,3,4], dtype="int8") # smaller integers

In [40]:
c.itemsize

1

In [41]:
c = np.array([1,3,4]).astype(np.int8)

In [42]:
c

array([1, 3, 4], dtype=int8)

In [43]:
new_array = np.array([1,2,True])

In [44]:
new_array

array([1, 2, 1])

In [45]:
(new_array).dtype

dtype('int32')

#### Array indexing

In [46]:
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [47]:
a[0]

array([0.69646919, 0.28613933, 0.22685145])

In [48]:
a[0,0]

0.6964691855978616

In [49]:
a[0,-1]

0.2268514535642031

In [50]:
a[0:2]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [51]:
a[0,1:3]

array([0.28613933, 0.22685145])

In [52]:
a[:,:]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

#### Modifying a slice will modify the array

In [53]:
a[0,0]

0.6964691855978616

In [54]:
a[0,0] = 10

In [55]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

#### Boolean indexing

In [ ]:
print(a)

In [56]:
bool_idx = (a > 0.7)
bool_idx

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [58]:
print(a[bool_idx])
#print(a[a > 0.7]) # in a single expression

[10.          0.71946897  0.9807642   0.72904971  0.73799541]


#### Reshaping arrays

In [59]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [61]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Subarrays return views, not copies!

In [63]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

In [64]:
# we take a slice of array "a" and store it in a new variable "a_chunk"
a_chunk = a[1:3, 0:2]
a_chunk

array([[0.55131477, 0.71946897],
       [0.9807642 , 0.68482974]])

In [65]:
# modifying "a_chung" also modifies "a"
a_chunk[0,0] = 0
print(a_chunk)
print("\n")
print(a)

[[0.         0.71946897]
 [0.9807642  0.68482974]]


[[10.          0.28613933  0.22685145]
 [ 0.          0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


#### Creating copies

In [ ]:
a_copy = a.copy()

In [ ]:
# modifying a copy does not modify the original
a_copy[0,0] = 0
print(a_copy, "\n")
print(a)

#### 3-D arrays

In [66]:
b = np.random.random((5,2,3))
print(b)

[[[0.53155137 0.53182759 0.63440096]
  [0.84943179 0.72445532 0.61102351]]

 [[0.72244338 0.32295891 0.36178866]
  [0.22826323 0.29371405 0.63097612]]

 [[0.09210494 0.43370117 0.43086276]
  [0.4936851  0.42583029 0.31226122]]

 [[0.42635131 0.89338916 0.94416002]
  [0.50183668 0.62395295 0.1156184 ]]

 [[0.31728548 0.41482621 0.86630916]
  [0.25045537 0.48303426 0.98555979]]]


### 4-D arrays

In [67]:
c = np.random.random((2,3,4,5))
print(c)

[[[[0.51948512 0.61289453 0.12062867 0.8263408  0.60306013]
   [0.54506801 0.34276383 0.30412079 0.41702221 0.68130077]
   [0.87545684 0.51042234 0.66931378 0.58593655 0.6249035 ]
   [0.67468905 0.84234244 0.08319499 0.76368284 0.24366637]]

  [[0.19422296 0.57245696 0.09571252 0.88532683 0.62724897]
   [0.72341636 0.01612921 0.59443188 0.55678519 0.15895964]
   [0.15307052 0.69552953 0.31876643 0.6919703  0.55438325]
   [0.38895057 0.92513249 0.84167    0.35739757 0.04359146]]

  [[0.30476807 0.39818568 0.70495883 0.99535848 0.35591487]
   [0.76254781 0.59317692 0.6917018  0.15112745 0.39887629]
   [0.2408559  0.34345601 0.51312815 0.66662455 0.10590849]
   [0.13089495 0.32198061 0.66156434 0.84650623 0.55325734]]]


 [[[0.85445249 0.38483781 0.3167879  0.35426468 0.17108183]
   [0.82911263 0.33867085 0.55237008 0.57855147 0.52153306]
   [0.00268806 0.98834542 0.90534158 0.20763586 0.29248941]
   [0.52001015 0.90191137 0.98363088 0.25754206 0.56435904]]

  [[0.80696868 0.39437005 0.73


### Operations:

- np.sum, np.multiply, np.power...

- np.mean, np.std...

In [68]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x**y  # works with *, /, **  element wise 

array([  1,  32, 729], dtype=int32)

Lists do not behave the same way: sum means concatenation

In [69]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [70]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x", "\n", x)
print("y", "\n", y)

x 
 [[1 2]
 [3 4]]
y 
 [[5 6]
 [7 8]]


In [71]:
print (x + y)

[[ 6  8]
 [10 12]]


In [72]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))
  
# Mean of each row in matrix a
print(np.mean(a, axis=1))

# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

[2.09157489 0.37929761 0.40557259]
[3.50433026 0.38085848 0.71550861 0.48811508 0.2987648  0.36531296]


0.536902908522835

In [73]:
# compute the standard deviation of this array, first using np.std() and then without using this function
np.random.seed(123)
rand = np.random.random(10)
rand

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [ ]:
squared_deviations = (rand - np.mean(rand))**2
squared_deviations

In [ ]:
np.sqrt(squared_deviations.mean())

In [ ]:
new_array = np.array([[1,2],[3,4],[5,6]])

In [74]:
new_array

array([1, 2, 1])

In [75]:
new_array.T

array([1, 2, 1])

#### Performance of numpy operations vs lists

In [76]:
from time import time

n = 1000000

start_time = time()

big_slow_list = []

for i in range(1, n):
    big_slow_list.append(i**3)

end_time = time()
    
print(end_time - start_time)

1.1223680973052979


In [77]:
n = 1000000

start_time = time()

big_fast_array = np.arange(1,n)**3

end_time = time()
    
print(end_time - start_time)

0.012998342514038086


#### Concatenate

In [ ]:
first = np.array([[1,2,3],[4,5,6]])
second = np.array([[0,0,0], [9,9,9]])

In [ ]:
first

In [ ]:
second

In [ ]:
np.concatenate([first, second])

In [ ]:
np.concatenate([first, second], axis=1)

In [ ]:
one_dim = np.array([1,1,1])

In [ ]:
np.vstack([first, one_dim])

### Transpose

In [ ]:
print(first)

In [ ]:
print(first.T)

#### Splitting arrays

In [ ]:
hundred = np.array(range(1,101))

In [ ]:
hundred

In [ ]:
first_half, second_half = np.split(hundred, [50])

In [ ]:
first_half

In [ ]:
second_half